name: flutter_actividad_whatsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/mi novia.jpg
  - assets/elian.jpg
  - assets/lalo.jpg
  - assets/naty.jpg
  - assets/jose lui.jpg
  - assets/magy.jpg
  - assets/familia.jpg
  - assets/mis amigos.jpg
  - assets/Sahira.jpg
  

